In [1]:
import requests
from bs4 import BeautifulSoup
import re
import pandas as pd
from time import time
def make_soup(url):
    content = requests.get(url)
    html_content=content.content
    soup=BeautifulSoup(html_content,'lxml')
    
    return soup

In [2]:
data_accident=[]
accident_time=[]
links=[]
for i in range(1,49):
    print(i)
    url2="https://www.dhakatribune.com/hashtag/road-accident/page/"+str(i)
    for el in make_soup(url2).find_all("h4",class_='news-title'):
        data_accident.append(el.get_text())
    
    for data_time in make_soup(url2).find_all("div",class_='listing-time'):
        accident_time.append(data_time.get_text())
    
    for link in make_soup(url2).find_all('div',class_='top-news'):
        links.append(link.a['href'])

print(len(data_accident))
print(len(accident_time))
print(len(links))

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
991
991
991

In [6]:
base_url='https://www.dhakatribune.com'
article_header=[]

for i in range(len(links)):
    url=base_url+links[i]
    print(i)
    for article in make_soup(url).find_all('div',class_='report-left report-mainhead'):
            article_header.append(article.h1.get_text())
    
    
print("Time is: ",round(time()-t0,3),"s")
print(len(article_header))

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
Time is:  2402.536 s
990

In [14]:
article_data=[]
for i in range(len(links)):
    print(i)article_data
    url=base_url+links[i]
    for article in make_soup(url).find_all('div',class_='report-content fr-view'):
            article_data.append(article.get_text())
print(len(article_data))

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
990

In [26]:
full_link=[]
for i in range(len(links)):
    url=base_url+links[i]
    full_link.append(url)
full_link.remove('https://www.dhakatribune.com/bangladesh/2016/06/22/3-killed-gazipur-road-accident')
print(len(full_link))

990

In [30]:
data_accident.remove('\n3 killed in Gazipur road accident\n')

In [32]:
accident_time.remove('\nBangladesh\nWed, Jun 22 2016 \n')

In [36]:
splitted_date=[]
for date_pattern in accident_time:
    x=date_pattern.split(",")
    splitted_date.append(x[1])

In [205]:
dataset={'Newspaper Name':'Dhaka Tribune','Accident date':splitted_date,'Header':article_header,'News title':data_accident,'Article':article_data,'Newspaper Link':full_link}

In [206]:
df=pd.DataFrame(dataset)

In [207]:
df.head()

,Newspaper Name,Accident date,Header,News title,Article,Newspaper Link
0,Dhaka Tribune,Jun 26 2021 \n,Two labourers killed in Dhaka road accident,\n2 killed in Dhaka road crash\n,\nTwo other workers have also been injured \nT...,https://www.dhakatribune.com/accident/2021/06/...
1,Dhaka Tribune,Jun 23 2021 \n,Three killed in Muktagacha road accident,\nThree killed in Muktagacha road...\n,\nThe deceased hailed from Muktagacha upazila’...,https://www.dhakatribune.com/accident/2021/06/...
2,Dhaka Tribune,Jun 19 2021 \n,Truck-pickup van collision leaves 3 dead in Na...,\nTruck-pickup van collision leaves 3...\n,\nTwo others seriously injured \nThree people ...,https://www.dhakatribune.com/bangladesh/nation...
3,Dhaka Tribune,Jun 19 2021 \n,"Couple, infant grandson killed in Bogra bus-au...",\nBogra road crash kills 3\n,\nInjured admitted to Shaheed Ziaur Rahman Med...,https://www.dhakatribune.com/bangladesh/nation...
4,Dhaka Tribune,Jun 19 2021 \n,Policeman killed in Dhaka road accident,\nCop killed in Dhaka road crash\n,\nBashir Talukder might have been hit by a veh...,https://www.dhakatribune.com/bangladesh/dhaka/...

In [208]:
date_list=[]
for a in df['Accident date']:
    b=a.strip()
    date_list.append(b)
df['Accident date']=date_list

In [209]:
accidentdata_refine=[]
for b in df['News title']:
    a=b.strip()
    accidentdata_refine.append(a)
df['News title']=accidentdata_refine

In [210]:

death=[]
for i in df['News title']:
    death.append(i)

In [211]:
import re
dead=[]
for a in death:
    death_count = re.findall('([^ \r\n]+) killed?',a)
    if death_count:
        dead.append(death_count)
    else:
        dead.append([''])


death_count=[]
for i in dead:
    for j in i:
        death_count.append(j)

        
a=['motorcyclists','assistant','Mother','Bangladeshis','bike','pedestrians','musicians','students','daughter','Bangladeshi','student','doctor','crashes','director','guards','family','Cop','Youth','bike','boy','Man','Woman','staff','Child','Boy','son','Women','women','Uddin','girl','DG','old','goers']

for i in death_count:
    if (len(i))>5:
        a.append(i)

In [212]:
filtered=[]
for i in range(0,5000):
    filtered.append(i)

from num2words import num2words
filtered_words=[]
for i in filtered:
    a=num2words(i)
    filtered_words.append(a)

In [213]:
count=[]
for i in death_count:
    if len(i)>5 or i == '':
        count.append('')
    else:
        for z in a:
            
            if i==z:
                count.append(c)
        for j in filtered:
            a=str(i)
            b=str(j)
            if a==b:
                count.append(a)
        for k in filtered_words:
            l=i.lower()
            if l==k:
                count.append(l)

In [214]:
len(count)

973

In [215]:
count.pop(2)

''

In [216]:
len(count)

972

In [217]:
for i in range(1,19):
    count.append('')

In [218]:
df.to_excel(r'DhakaTribuneDatasettry.xlsx')

In [219]:
df['Deaths']=count

In [220]:
del(df['Newspaper Link'])
del(df['Article'])
df.to_excel(r'DhakaTribuneDataset.xlsx')

In [221]:
df.head()

,Newspaper Name,Accident date,Header,News title,Deaths
0,Dhaka Tribune,Jun 26 2021,Two labourers killed in Dhaka road accident,2 killed in Dhaka road crash,2
1,Dhaka Tribune,Jun 23 2021,Three killed in Muktagacha road accident,Three killed in Muktagacha road...,three
2,Dhaka Tribune,Jun 19 2021,Truck-pickup van collision leaves 3 dead in Na...,Truck-pickup van collision leaves 3...,
3,Dhaka Tribune,Jun 19 2021,"Couple, infant grandson killed in Bogra bus-au...",Bogra road crash kills 3,3
4,Dhaka Tribune,Jun 19 2021,Policeman killed in Dhaka road accident,Cop killed in Dhaka road crash,

Manually managed the data and again uploaded for removing not required columns and rows.

In [222]:
dataframe=pd.read_excel('DhakaTribuneDataset.xlsx')

In [223]:
dataframe.head()

,Unnamed: 0,Newspaper Name,Accident date,Header,News title,Deaths,Injured
0,0,Dhaka Tribune,Jun 26 2021,Two labourers killed in Dhaka road accident,2 killed in Dhaka road crash,2,2.0
1,1,Dhaka Tribune,Jun 23 2021,Three killed in Muktagacha road accident,Three killed in Muktagacha road...,3,NaN
2,2,Dhaka Tribune,Jun 19 2021,Truck-pickup van collision leaves 3 dead in Na...,Truck-pickup van collision leaves 3...,3,NaN
3,3,Dhaka Tribune,Jun 19 2021,"Couple, infant grandson killed in Bogra bus-au...",Bogra road crash kills 3,3,NaN
4,4,Dhaka Tribune,Jun 19 2021,Policeman killed in Dhaka road accident,Cop killed in Dhaka road crash,1,NaN

In [230]:
dataframe=dataframe.drop(labels=[37,78,69,79,81,87,92,95,96,97,103,107,113,119,123,130,135,136,137,138,145,147,162,166,168,187,192,209,229,232,253,267,282,308,312,316,321,322,336,338,339,340,341,350,362,373,377,378,379,383,384,387,392,406,413,423,429,430,442,445,446,449,450,465,466], axis=0)

In [256]:
dataframe['Injured']=dataframe['Injured'].fillna(0)

In [258]:
dataframe['Injured']=dataframe['Injured'].apply(int)

In [263]:
dataframe=dataframe.drop(columns=['Unnamed: 0'])

In [269]:
dataframe.to_csv(r'dhakatribunedataset.csv')